stages:
  data_prepare:
    cmd: python -m src.stages.data_prepare --config=params.yaml
    deps:
    - src/stages/data_prepare.py
    params:
    - base
    - data_load
    outs:
    - data/processed/prepare_penguins.csv
